import { StyleSheet, Dimensions } from "react-native";

export const navBar = StyleSheet.create({
    header: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 20,
        marginTop: 10,
    },
    title: {
        flex: 1,
        fontSize: 50,
        fontFamily: "BungeeShade-Regular",
        fontWeight: "bold",
        color: "#000",
        paddingTop: "1%",
        paddingHorizontal: "1%",
    },
    home: { paddingHorizontal: "1%",},
    search: { paddingHorizontal: "1%" },
    setup: { paddingHorizontal: "1%" },
    settings: { paddingHorizontal: "1%" },
})

export const indexStyle = StyleSheet.create({
    background: {
        flex: 1,
        width: '100%',
        height: '100%',
    },
    safeArea: {
        flex: 1,
    },
    scrollContainer: {
        flexGrow: 1,
        paddingVertical: '4%',
        alignItems: 'center',
        justifyContent: 'flex-start',
    },
    container: {
        flex: 1,
        width: '75%',
        backgroundColor: 'rgba(254, 253, 252, 0.85)',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 50,
    },
    title: {
        paddingVertical: '1%',
        fontFamily: "BungeeShade-Regular", 
        fontSize: 140, 
        fontWeight: 'bold', 
        textAlign: 'center',
        justifyContent: 'flex-start',
        color: '#093001',
    },
    subtextContainer: {
        fontFamily: 'Roboto-LightItalic',
        fontSize: 20, 
        textAlign: 'center', 
        marginTop: '2%',
        color: '#093001',
    },
    top_button: { 
        marginVertical: 5, 
        marginTop: '1%',
        width: "45%", 
        backgroundColor: "#45332b",
    },
    bottom_button: { 
        marginTop: '1%', 
        marginBottom: '2%',
        width: "45%",
        backgroundColor: "#1f1714",
    },
})

export const loginStyle = StyleSheet.create({
    background: {
        flex: 1,
        width: '100%',
        height: '100%',
    },
    safeArea: {
        flex: 1,
    },
    scrollContainer: {
        flexGrow: 1,
        paddingVertical: '4%',
        alignItems: 'center',
        justifyContent: 'flex-start',
    },
    container: {
        flex: 1,
        width: '75%',
        backgroundColor: 'rgba(254, 253, 252, 0.85)',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 50,
    },
    title: {
        marginTop: '1%',
        fontFamily: "BungeeShade-Regular", 
        fontSize: 140, 
        fontWeight: 'bold', 
        textAlign: 'center',
        justifyContent: 'flex-start',
        color: '#093001',
    },
    email_input: {
        borderRadius: 20,
        borderWidth: 2,
        minHeight: 45,
        marginTop: '5%',
        paddingHorizontal: 20,
        width: "45%",
        justifyContent: "center",
        alignItems: "center",
        flexDirection: "row",
        borderColor: "#093001",
        backgroundColor: "#fff",   
        fontFamily: 'Roboto-Regular',
        color: '#072404',
    },
    password_input: {
        borderRadius: 20,
        borderWidth: 2,
        minHeight: 45,
        marginTop: '1%',
        paddingHorizontal: 20,
        width: "45%",
        justifyContent: "center",
        alignItems: "center",
        flexDirection: "row",
        borderColor: "#093001",
        backgroundColor: "#fff",   
        fontFamily: 'Roboto-Regular',
        color: '#072404',
    },
    button: { 
        marginVertical: 5, 
        marginTop: '1%',
        width: "45%", 
        backgroundColor: "#1f1714"
    },
    linkText: {
        marginTop: '2%',
        marginBottom: '2%',
        color: "#093001",
        fontSize: 20,
        fontFamily: 'Roboto-Italic',
        textDecorationLine: "underline",
    },
})

export const signupStyle = StyleSheet.create({
    background: {
        flex: 1,
        width: '100%',
        height: '100%',
    },
    safeArea: {
        flex: 1,
    },
    scrollContainer: {
        flexGrow: 1,
        paddingVertical: '2%',
        alignItems: 'center',
        justifyContent: 'flex-start',
    },
    container: {
        flex: 1,
        width: '75%',
        backgroundColor: 'rgba(254, 253, 252, 0.85)',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 50,
    },
    title: {
        marginTop: '1%',
        fontFamily: "BungeeShade-Regular", 
        fontSize: 140, 
        fontWeight: 'bold', 
        textAlign: 'center',
        justifyContent: 'flex-start',
        color: '#093001',
    },
    username_input: {
        borderRadius: 20,
        borderWidth: 2,
        minHeight: 45,
        marginTop: '4%',
        paddingHorizontal: 20,
        width: "45%",
        justifyContent: "center",
        alignItems: "center",
        flexDirection: "row",
        borderColor: "#093001",
        backgroundColor: "#fff",   
        fontFamily: 'Roboto-Regular',
        color: '#072404',
    },
    email_input: {
        borderRadius: 20,
        borderWidth: 2,
        minHeight: 45,
        marginTop: '1%',
        paddingHorizontal: 20,
        width: "45%",
        justifyContent: "center",
        alignItems: "center",
        flexDirection: "row",
        borderColor: "#093001",
        backgroundColor: "#fff",   
        fontFamily: 'Roboto-Regular',
        color: '#072404',
    },
    password_input: {
        borderRadius: 20,
        borderWidth: 2,
        minHeight: 45,
        marginTop: '1%',
        paddingHorizontal: 20,
        width: "45%",
        justifyContent: "center",
        alignItems: "center",
        flexDirection: "row",
        borderColor: "#093001",
        backgroundColor: "#fff",   
        fontFamily: 'Roboto-Regular',
        color: '#072404',
    },
    button: { 
        marginVertical: 5, 
        marginTop: '1%',
        width: "45%", 
        backgroundColor: "#1f1714"
    },
    linkText: {
        marginTop: '2%',
        marginBottom: '2%',
        color: "#093001",
        fontSize: 20,
        fontFamily: 'Roboto-Italic',
        textDecorationLine: "underline",
    },
})

export const homeStyle = StyleSheet.create({
    background: {
        flex: 1,
        resizeMode: "contain",
        width: "100%",
        height: "100%",
    },
    safeArea: {
        flex: 1,
    },
    scrollContainer: {
        flexGrow: 1,
        width: '100%',
        paddingVertical: '1%',
        alignItems: 'center',
        justifyContent: 'flex-start',
    },
    container: {
        width: '95%',
    },
    sensorCard: {
        flexDirection: "column",
        marginBottom: "5%",
        backgroundColor: "rgba(255, 255, 255, 0.6)",
        borderRadius: 12,
        padding: 10,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
    },
    deviceHeader: {
        backgroundColor: "rgba(255, 255, 255, 0.9)",
        paddingVertical: 10,
        paddingHorizontal: 15,
        borderRadius: 8,
        width: "95%",
        alignSelf: "center",
        marginBottom: 10,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
    },
    deviceId: {
        fontSize: 25,
        color: "#333",
        fontFamily: "Roboto-Regular",
        textAlign: "center",
    },
    divider: {
        marginTop: 8,
        height: 1,
        backgroundColor: "#ccc",
        width: "100%",
    },
    tempandhum: {
        flexDirection:'column',
        width: '10%',
        marginLeft: '3%',
    },
    tempcontainer: {
        borderRadius: 20,
        height: 135,
        marginTop: '10%',
        width: '125%',
        flexDirection:'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.4,
        shadowRadius: 8,
    },
    temphoverContainer: {
        //opacity: 1,
        transform: [{ scale: 1.25 }],
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.4,
        shadowRadius: 8,
    },
    temp: {
        fontSize: 25,
        fontFamily: 'Roboto-Regular',
        color: '#000',
        paddingHorizontal: '5%',
    },
    humiditycontainer: { 
        borderRadius: 20,
        height: 135,
        width: '125%',
        marginTop: '15%',
        flexDirection:'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.4,
        shadowRadius: 8,
    },
    humhoverContainer: {
        //opacity: 1,
        transform: [{ scale: 1.25 }],
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.4,
        shadowRadius: 8,
    },
    humidity: {
        fontSize: 25,
        fontFamily: 'Roboto-Regular',
        color: '#000',
        paddingHorizontal: '5%',
    },
    containrest: {
        flexDirection: 'row',
        marginTop: '1%',
        marginLeft: '4%',
        width: '75%',
    },
    lightcontainer: { 
        borderRadius: 20,
        height: 300,
        width: '30%',
        flexDirection:'column',
        alignItems: 'flex-start',
        justifyContent: 'flex-start',
        padding: 20,
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.4,
        shadowRadius: 8,
    },
    lightHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10, // spacing between label row and chart
    },
    light: {
        fontSize: 25,
        fontFamily: 'Roboto-Regular',
        color: '#000',
        paddingHorizontal: '2%',
        paddingVertical: '1%'
    },
    soilcontainer: {
        borderRadius: 20,
        height: 300,
        marginLeft: '2%',
        width: '30%',
        flexDirection:'column',
        alignItems: 'flex-start',
        justifyContent: 'flex-start',
        padding: 20,
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.4,
        shadowRadius: 8,
    },
    soilHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: '2%',
        marginBottom: 10, // spacing between label row and chart
    },
    soil: {
        fontSize: 23,
        fontFamily: 'Roboto-Regular',
        color: '#000',
        paddingVertical: '1%',
    
    },
    plantContainer: {
        borderRadius: 20,
        height: 300,
        marginLeft: '2%',
        width: "40%",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "rgba(254, 253, 252, 0.85)",
        padding: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.4,
        shadowRadius: 8,
    },
    plantImage: {
        width: "100%",
        height: 200,
        borderRadius: 12,
        resizeMode: "cover",
        marginBottom: 8,
    },
    plantName: {
        color: "#333",
        textAlign: "center",
        fontSize: 23,
        fontFamily: 'Roboto-Regular',
        color: '#000',
    },
    editButton: {
        marginTop: 8,
        fontSize: 16,
        textDecorationLine: "underline",
        color: "#000",
        textAlign: "center",
        fontSize: 15,
        fontFamily: 'Roboto-Italic',
    },
    plantPlaceholder: {
        width: "100%",
        height: 200,
        backgroundColor: "#ddd",
        borderRadius: 12,
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 8,
        fontSize: 15,
        fontFamily: 'Roboto-Regular',
    },
    timestamp: {
        fontSize: 14,
        fontFamily: 'Roboto-Italic',
        color: "#444",
        marginTop: 10,
        marginLeft: 5,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(0,0,0,0.5)",
        justifyContent: "center",
        alignItems: "center",
    },
    modalContainer: {
        backgroundColor: "#fff",
        borderRadius: 12,
        padding: 20,
        width: "90%",
        height: "50%",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
    },
    modalTitle: {
        fontSize: 25,
        fontFamily: 'Roboto-Regular',
        marginTop: 10,
        marginBottom: 10,
        textAlign: "center",
    },
    modalItem: {
        marginTop: 15,
        fontSize: 18,
        fontFamily: 'Roboto-Regular',
        paddingVertical: 13,
        borderBottomWidth: 1,
        borderBottomColor: "#ccc",
        textAlign: "center",
    },
    modalCancel: {
        fontSize: 18,
        marginTop: 25,
        textAlign: "center",
        fontFamily: 'Roboto-Regular',
        color: "red",
    },
})

const SEARCH_WIDTH = Dimensions.get("window").width / 5 - 16;
export const searchStyle = StyleSheet.create({
    background: {
        flex: 1,
        width: "100%",
        height: "100%",
    },
    safeArea: {
        flex: 1,
    },
    scrollContainer: {
        flexGrow: 1,
        paddingVertical: "1%",
        alignItems: "center",
        justifyContent: "flex-start",
    },
    container: {
        width: "100%",
        justifyContent: "center",
        alignItems: "center",
        borderRadius: 50,
    },
    searchInput: {
        borderRadius: 20,
        borderWidth: 2,
        minHeight: 50,
        marginTop: "1%",
        marginBottom: 10,
        paddingHorizontal: 20,
        width: "80%",
        borderColor: "#093001",
        backgroundColor: "#fff",
        fontFamily: "Roboto-Regular",
        color: "#072404",
    },
    cardGrid: {
        paddingBottom: 20,
        paddingHorizontal: 10,
    },
    plantCard: {
        backgroundColor: "#fff",
        borderRadius: 10,
        padding: 6,
        marginVertical: 6,
        marginHorizontal: 6,
        width: SEARCH_WIDTH,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 2,
        alignItems: "center",
    },
    plantImage: {
        width: "100%",
        aspectRatio: 1,
        borderRadius: 8,
        marginBottom: 4,
        resizeMode: "cover",
        backgroundColor: "#f0f0f0",
    },
    cardTitle: {
        fontSize: 24,
        fontWeight: "500",
        color: "#333",
        textAlign: "center",
        fontFamily: "Roboto-Regular",
    },
    cardText: {
        fontSize: 20,
        color: "#555",
        marginBottom: 3,
        textAlign: "center",
        fontFamily: "Roboto-Regular",
    },
    emptyText: {
        marginTop: "5%",
        fontSize: 16,
        color: "#444",
    },
    modalOverlay: {
        position: "absolute",
        top: 0,
        left: 0,
        height: "100%",
        width: "100%",
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "rgba(0,0,0,0.5)",
        padding: 20,
    },
    modalBackdrop: {
        backgroundColor: "#fff",
        borderRadius: 16,
        padding: 20,
        alignItems: "center",
        width: SEARCH_WIDTH + 40,
        maxWidth: 500,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 5,
        elevation: 5,
    },
    modalContent: {
        alignItems: "center",
    },
    modalTitle: {
        fontSize: 25,
        fontWeight: "bold",
        marginBottom: 10,
        textAlign: "center",
        fontFamily: "Roboto-Regular",
    },
    modalImage: {
        width: SEARCH_WIDTH,
        aspectRatio: 1,
        borderRadius: 8,
        marginBottom: 10,
        resizeMode: "cover",
        backgroundColor: "#f0f0f0",
    },
    modalCloseArea: {
        position: "absolute",
        top: 8,
        right: 12,
        zIndex: 10,
    },
    modalCloseText: {
        fontSize: 24,
        color: "#888",
        fontFamily: "Roboto-Regular",
    },
})

export const settingsStyle = StyleSheet.create({
    background: {
        flex: 1,
        resizeMode: "contain",
        width: "100%",
        height: "100%",
    },
    container: {
        width: "100%",
        alignItems: "center",
        paddingTop: 100,
        paddingBottom: 80,
    },
    settingsBox: {
        backgroundColor: "#fff",
        width: "100%",
        maxWidth: 500,        
        borderRadius: 20,
        padding: 20,
        marginTop: 5,
        elevation: 4,
        alignSelf: "center",      
    },  
    label: {
        //fontWeight: "bold",
        fontSize: 20,
        marginBottom: 4,
        color: "#333",
        fontFamily: "Roboto-Regular",
    },
    input: {
        borderWidth: 1,
        borderColor: "#ccc",
        borderRadius: 10,
        padding: 10,
        marginBottom: 15,
        backgroundColor: "#fafafa",
        fontFamily: "Roboto-Regular",
    },
    toggleRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 15,
    },
    dropdownRow: {
        marginBottom: 25,
    },
    dropdownText: {
        fontSize: 14,
        color: "#666",
        marginTop: 4,
        fontFamily: "Roboto-Regular",
    },
    button: {
        backgroundColor: "#5DB075",
        padding: 14,
        borderRadius: 10,
        alignItems: "center",
        marginTop: 10,
    },
    buttonText: {
        color: "white",
        fontWeight: "bold",
        fontFamily: "Roboto-Regular",
    },
    deleteButton: {
        padding: 14,
        marginTop: 20,
        alignItems: "center",
    },
    deleteText: {
        color: "red",
        fontWeight: "bold",
        fontFamily: "Roboto-Regular",
    },
})

//const CARD_WIDTH = Dimensions.get("window").width > 600 ? 500 : Dimensions.get("window").width * 0.92;
export const setupStyle = StyleSheet.create({
    background: {
        flex: 1,
        resizeMode: "cover",
        width: "100%",
        height: "100%",
    },
    container: {
        alignItems: "center",
        padding: 20,
        paddingTop: 30,
        paddingBottom: 60,
    },
    heading: {
        fontSize: 45,
        fontFamily: "BungeeShade-Regular",
        fontWeight: "bold",
        color: "#000",
        textAlign: "center",
        marginBottom: 25,
    },
    card: {
        backgroundColor: "#fff",
        width: '60%',
        borderRadius: 20,
        padding: 20,
        marginBottom: 25,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 6,
        elevation: 5,
    },
    sectionTitle: {
        fontFamily: "Roboto-Regular",
        fontSize: 22,
        fontWeight: "600",
        marginBottom: 10,
        color: "#333",
    },
    instruction: {
        marginTop: 5,
        fontFamily: "Roboto-Regular",
        fontSize: 18,
        color: "#444",
        marginBottom: 8,
    },
    bold: {
        fontWeight: "bold",
    },
    faqText: {
        fontFamily: "Roboto-Regular",
        fontSize: 16,
        color: "#666",
        marginBottom: 10,
        marginLeft: 10,
    },
})